### PR TITLE
feat: Switch to using URL property for tags

### PR DESCRIPTION
**Pull request by matthew-andrews**
@andygnewman - probably another major version

### CODE REVIEW

**Comment by andygnewman** [comment]
hmm, not sure it would need to be a major version. The field is essentially remaining the same as a relative path, just pointing at a vanity rather than actual, unless I'm missing something here.

**Comment by matthew-andrews** [comment]
i think the graphql uses of this may need to have their queries updated, but might be safe

**Comment by andygnewman** [comment]
I think the graphql queries had to be updated anyway because the latest n-card uses url property for link generation. Caused a few issues at the time which had to be resolved.

**Comment by matthew-andrews** [comment]
ok well if you think it's safe to make a minor, i'd be happy to do that!  saves some effort :)

**Comment by matthew-andrews** [comment]
i will manually check the front page and if ok, hit MERGE

**Comment by matthew-andrews** [comment]
yup seems safe

**Pull request merged**
